version: "3.6"

services:
  so1:
    image: splunk/splunk:latest
    container_name: splunkenterprise
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_USER=root
      - SPLUNK_PASSWORD=password
    ports:
      - 8000:8000
      - 8089:8089
      - 9997:9997
    volumes:
      - opt-splunk-etc:/opt/splunk/etc
      - opt-splunk-var:/opt/splunk/var
volumes:
  opt-splunk-etc:
  opt-splunk-var: